### ISSUE TITLE
Botón flotante de reportes en vista de Campañas.

### ISSUE THREAD

**Issue by mariobp** [exildev/CiclosAndroid#4]
Es la misma url: /reportes/reporte/form/
Pero ahora recibe en vez de una piscina una campaña, ese es el único cambio, así que en donde iba la vista de piscinas ahora va la vista de campaña.

**Comment by Cromeror** [comment]
NOTE: Reemplazar el spinner de piscinas por campañas, loo puedo encontrar en ReporteActivity método setPiscinaSpinner(JSONArray).

**Comment by Cromeror** [comment]
Aun presenta un error al enviar el reporte. al rellenar todos los campos y enviar el reporte este muestra una notificación de error, pero no indica que error sucedió.

**Comment by Cromeror** [comment]
Aun presenta un error al enviar el reporte. al rellenar todos los campos y enviar el reporte este muestra una notificación de error, pero no indica que error sucedió.

**Comment by mariobp** [comment]
Ok revisaré el servicio.
